name: Build ZMK firmware

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      board: ble_micro_pro
      shield: |
        settings_reset
        torabo_tsuki_central
        torabo_tsuki_left_peripheral
        torabo_tsuki_right_peripheral
